alternative_signs: {  }
ISO4217Code: DDM
minorUnit: null
ISO4217Number: '278'
sign: ¤
title: 'East German Mark of the GDR'
usage:
    - { ISO8601From: '1948-07-20', ISO8601To: '1990-10-02', ISO3166Code: DD }
