alternative_signs: {  }
ISO4217Code: GQE
minorUnit: null
ISO4217Number: null
sign: ¤
title: 'Equatorial Guinean ekwele'
usage:
    - { ISO8601From: '1975-07-07', ISO8601To: '1986-06-01', ISO3166Code: GQ }
